import { StyleSheet } from 'react-native';

export const colors = { background: '#071116', card: '#101f25', border: '#293d46', text: '#edf4f5', muted: '#9aacb3', accent: '#39dbc1', loss: '#ff808a', tabText: '#c6d1d5', tabActive: '#8cf5df' };
export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  content: { padding: 20, gap: 18, paddingBottom: 126, width: '100%', maxWidth: 760, alignSelf: 'center' },
  card: { padding: 18, gap: 14, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: 20 },
  row: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  between: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 },
  wrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  grow: { flex: 1 },
  title: { color: colors.text, fontSize: 28, fontWeight: '700' },
  heading: { color: colors.text, fontSize: 20, fontWeight: '700' },
  text: { color: colors.text, fontSize: 15, lineHeight: 22 },
  muted: { color: colors.muted, fontSize: 13, lineHeight: 19 },
  label: { color: colors.muted, fontSize: 11, letterSpacing: 1.4, fontWeight: '600' },
  total: { color: colors.text, fontSize: 34, fontWeight: '700', fontVariant: ['tabular-nums'] },
  number: { color: colors.text, fontSize: 17, fontWeight: '600', fontVariant: ['tabular-nums'] },
  positive: { color: colors.accent },
  negative: { color: colors.loss },
  button: { minHeight: 44, paddingHorizontal: 16, paddingVertical: 12, borderRadius: 12, backgroundColor: colors.accent, justifyContent: 'center', alignItems: 'center' },
  buttonText: { color: colors.background, fontWeight: '700', fontSize: 14 },
  secondary: { backgroundColor: '#1c333b' },
  secondaryText: { color: colors.text },
  disabled: { opacity: 0.45 },
  input: { color: colors.text, backgroundColor: colors.background, borderColor: colors.border, borderWidth: 1, borderRadius: 12, padding: 13, fontSize: 16, minHeight: 48 },
  field: { gap: 7 },
  divider: { borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 14 },
  logo: { width: 48, height: 48, borderRadius: 12, backgroundColor: '#ffffff', borderWidth: 1, borderColor: colors.border },
  logoFallback: { width: 48, height: 48, borderRadius: 12, backgroundColor: '#1c333b', alignItems: 'center', justifyContent: 'center' },
  tabBar: { position: 'absolute', width: '94%', maxWidth: 960, alignSelf: 'center', bottom: 8, height: 86, borderRadius: 34, borderWidth: 1, borderColor: '#52626a', overflow: 'hidden', backgroundColor: 'rgba(18,36,44,0.88)' },
  tabBarInner: { flex: 1, flexDirection: 'row', alignItems: 'stretch', padding: 7, gap: 2 },
  tabItem: { flex: 1, minWidth: 0, borderRadius: 27, alignItems: 'center', justifyContent: 'center', gap: 5, paddingHorizontal: 2 },
  tabItemActive: { backgroundColor: 'rgba(105,150,153,0.36)' },
  tabLabel: { color: colors.tabText, fontSize: 11, fontWeight: '600', textAlign: 'center', width: '100%' },
  tabLabelActive: { color: colors.tabActive },
  chartCard: { padding: 18, gap: 14, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: 20 },
  chartCenter: { height: 170, alignItems: 'center', justifyContent: 'center' },
  donutLabel: { position: 'absolute', alignItems: 'center', justifyContent: 'center' },
  legend: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  legendDot: { width: 9, height: 9, borderRadius: 5 },
  center: { alignItems: 'center', justifyContent: 'center', padding: 28, gap: 16 },
});
