import { StyleSheet } from 'react-native';

export const colors = { background: '#090f18', card: '#131e2c', border: '#263448', text: '#edf4f5', muted: '#9aacb3', accent: '#39dbc1', loss: '#ff808a', tabText: '#c6d1d5', tabActive: '#8cf5df' };
export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  content: { padding: 16, gap: 12, paddingBottom: 140, width: '100%', maxWidth: 760, alignSelf: 'center' },
  card: { padding: 16, gap: 10, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: 24 },
  row: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  between: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 },
  wrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  grow: { flex: 1, minWidth: 0 },
  title: { fontFamily: 'GoogleSans-Bold', color: colors.text, fontSize: 28, letterSpacing: -0.8 },
  wordmark: { fontFamily: 'GoogleSans-Bold', color: '#ffffff', fontSize: 26, letterSpacing: -1.1 },
  wordmarkAccent: { color: '#22e6a2' },
  splashLogo: { width: 240, height: 240, maxWidth: '100%' },
  heading: { fontFamily: 'GoogleSans-Bold', color: colors.text, fontSize: 20 },
  text: { fontFamily: 'GoogleSans-Regular', color: colors.text, fontSize: 15, lineHeight: 22 },
  muted: { fontFamily: 'GoogleSans-Regular', color: colors.muted, fontSize: 13, lineHeight: 19 },
  label: { fontFamily: 'GoogleSans-SemiBold', color: colors.muted, fontSize: 11, letterSpacing: 1.4 },
  total: { fontFamily: 'GoogleSans-Bold', color: colors.text, fontSize: 36, letterSpacing: -1.2, fontVariant: ['tabular-nums'] },
  number: { fontFamily: 'GoogleSans-SemiBold', color: colors.text, fontSize: 17, fontVariant: ['tabular-nums'] },
  positive: { color: colors.accent },
  negative: { color: colors.loss },
  button: { minHeight: 48, paddingHorizontal: 16, paddingVertical: 12, borderRadius: 12, backgroundColor: colors.accent, justifyContent: 'center', alignItems: 'center' },
  buttonText: { fontFamily: 'GoogleSans-Bold', color: colors.background, fontSize: 14 },
  secondary: { backgroundColor: '#203247' },
  secondaryText: { color: colors.text },
  disabled: { opacity: 0.45 },
  input: { fontFamily: 'GoogleSans-Regular', color: colors.text, backgroundColor: colors.background, borderColor: colors.border, borderWidth: 1, borderRadius: 12, padding: 13, fontSize: 16, minHeight: 48 },
  field: { gap: 7 },
  divider: { borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 10 },
  logo: { width: 48, height: 48, borderRadius: 12, backgroundColor: '#ffffff', borderWidth: 1, borderColor: colors.border },
  logoFallback: { width: 48, height: 48, borderRadius: 12, backgroundColor: '#203247', alignItems: 'center', justifyContent: 'center' },
  tabBar: { position: 'absolute', width: '94%', maxWidth: 720, alignSelf: 'center', borderRadius: 26, borderWidth: 1, borderColor: colors.border, overflow: 'hidden', backgroundColor: 'rgba(19,30,44,0.96)' },
  tabBarInner: { flexGrow: 1, flexDirection: 'row', alignItems: 'stretch', padding: 8, gap: 4 },
  tabItem: { flex: 1, minWidth: 0, minHeight: 48, borderRadius: 19, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 2, paddingVertical: 12 },
  tabItemActive: { backgroundColor: '#25443f' },
  tabLabel: { fontFamily: 'GoogleSans-SemiBold', color: colors.tabText, fontSize: 12, textAlign: 'center' },
  tabLabelActive: { color: colors.tabActive },
  chartCard: { padding: 16, gap: 10, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: 24 },
  chartCenter: { height: 170, alignItems: 'center', justifyContent: 'center' },
  donutLabel: { position: 'absolute', alignItems: 'center', justifyContent: 'center' },
  legend: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  legendDot: { width: 9, height: 9, borderRadius: 5 },
  hero: { backgroundColor: '#173b39', borderColor: '#2b5d54', padding: 18, gap: 12, overflow: 'hidden' },
  heroLabel: { fontFamily: 'GoogleSans-Bold', color: '#b9d8cf', fontSize: 11, letterSpacing: 1.8 },
  heroValue: { fontFamily: 'GoogleSans-Bold', color: '#f2fff8', fontSize: 42, letterSpacing: -1.8, fontVariant: ['tabular-nums'] },
  heroMetrics: { flexDirection: 'row', gap: 16, borderTopWidth: 1, borderTopColor: '#386058', paddingTop: 12 },
  metricTile: { flex: 1, minWidth: 0, padding: 12, borderRadius: 20, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, gap: 8 },
  badge: { alignSelf: 'flex-start', backgroundColor: '#234b44', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8 },
  sectionTitle: { fontFamily: 'GoogleSans-Bold', color: colors.text, fontSize: 20, letterSpacing: -0.4 },
  quickAction: { flex: 1, minWidth: 0, minHeight: 76, padding: 12, borderRadius: 18, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, gap: 8 },
  quickActionLabel: { fontFamily: 'GoogleSans-SemiBold', color: colors.text, fontSize: 13 },
  statusRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  statusDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.muted },
  allocationTrack: { height: 5, borderRadius: 3, backgroundColor: colors.border, overflow: 'hidden' },
  allocationFill: { height: 5, borderRadius: 3, backgroundColor: colors.accent },
  header: { gap: 10 },
  centeredText: { textAlign: 'center' },
  emptyState: { alignItems: 'center', paddingVertical: 14, paddingHorizontal: 10, gap: 8 },
  emptyIcon: { width: 60, height: 60, borderRadius: 20, backgroundColor: '#203b3b', alignItems: 'center', justifyContent: 'center', marginBottom: 4 },
  inset: { backgroundColor: '#0d1723', borderRadius: 16, padding: 12, gap: 8 },
  allocationLegend: { gap: 10 },
  allocationLegendRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  progressTrack: { height: 8, borderRadius: 4, backgroundColor: colors.border, overflow: 'hidden' },
  progressFill: { height: 8, borderRadius: 4, backgroundColor: colors.accent },
  tabIndicator: { position: 'absolute', bottom: 5, width: 4, height: 4, borderRadius: 2, backgroundColor: colors.tabActive },
  inputFocused: { borderColor: colors.accent, backgroundColor: '#10252b' },
  pressed: { opacity: 0.75 },
  center: { alignItems: 'center', justifyContent: 'center', padding: 28, gap: 16 },
});
