import {
  ArrowCounterClockwise,
  ArrowDown,
  ArrowUp,
  ArrowsClockwise,
  ChartBar,
  ChartLineUp,
  ChartPieSlice,
  Check,
  Cloud,
  CloudArrowUp,
  CloudCheck,
  CloudWarning,
  Coins,
  DownloadSimple,
  DotsThreeVertical,
  Folder,
  List,
  Money,
  Plus,
  Receipt,
  SignOut,
  SlidersHorizontal,
  Target,
  UploadSimple,
  UserCircle,
  Wallet,
  X,
} from '@phosphor-icons/react';

const ICONS = {
  overview: ChartPieSlice,
  growth: ChartLineUp,
  investments: Wallet,
  liabilities: Receipt,
  targets: Target,
  stocks: ChartBar,
  export: UploadSimple,
  import: DownloadSimple,
  reset: ArrowCounterClockwise,
  signout: SignOut,
  menu: List,
  add: Plus,
  remove: X,
  refresh: ArrowsClockwise,
  sort: SlidersHorizontal,
  up: ArrowUp,
  down: ArrowDown,
  portfolios: Folder,
  cash: Money,
  dividend: Coins,
  value: Wallet,
  synced: CloudCheck,
  syncing: CloudArrowUp,
  syncerror: CloudWarning,
  local: Cloud,
  more: DotsThreeVertical,
  check: Check,
  profile: UserCircle,
};

export default function AppIcon({ name, size = 20, weight = 'duotone', ...props }) {
  const Icon = ICONS[name] || Wallet;
  return <Icon size={size} weight={name === 'add' ? 'bold' : weight} aria-hidden="true" {...props} />;
}
