import {
  ArrowDown,
  ArrowUp,
  Banknote,
  Car,
  ChartBar,
  ChartPie,
  CircleGauge,
  Check,
  Cloud,
  CloudAlert,
  CloudCheck,
  CloudUpload,
  Coins,
  Cog,
  CreditCard,
  Download,
  Droplets,
  EllipsisVertical,
  Folder,
  Flower2,
  FlaskConical,
  Fuel,
  Landmark,
  Leaf,
  List,
  LogOut,
  Moon,
  Package,
  Plus,
  Receipt,
  RefreshCcw,
  RefreshCw,
  SlidersHorizontal,
  Shovel,
  Sprout,
  Store,
  Target,
  Tractor,
  TrendingUp,
  Truck,
  Sun,
  Upload,
  UserCircle,
  Wallet,
  WavesHorizontal,
  X,
  Zap,
} from '@sketchyicons/react';

const ICONS = {
  overview: ChartPie,
  growth: TrendingUp,
  investments: Wallet,
  liabilities: Receipt,
  targets: Target,
  stocks: ChartBar,
  export: Upload,
  import: Download,
  reset: RefreshCcw,
  signout: LogOut,
  menu: List,
  add: Plus,
  remove: X,
  refresh: RefreshCw,
  sort: SlidersHorizontal,
  up: ArrowUp,
  down: ArrowDown,
  portfolios: Folder,
  cash: Banknote,
  dividend: Coins,
  value: Wallet,
  synced: CloudCheck,
  syncing: CloudUpload,
  syncerror: CloudAlert,
  local: Cloud,
  more: EllipsisVertical,
  check: Check,
  profile: UserCircle,
  light: Sun,
  dark: Moon,
  tractor: Tractor,
  tyre: CircleGauge,
  transportation: Truck,
  fuel: Fuel,
  oilGas: Droplets,
  plants: Leaf,
  soil: Shovel,
  fertilizers: Flower2,
  sprout: Sprout,
  engine: Cog,
  cars: Car,
  electricity: Zap,
  chemicals: FlaskConical,
  waving: WavesHorizontal,
  cement: Package,
  banks: Landmark,
  merchantAccounts: Store,
  creditCard: CreditCard,
};

export default function AppIcon({ name, size = 20, weight: _weight, ...props }) {
  const Icon = ICONS[name] || Wallet;
  return <Icon size={size} strokeWidth={name === 'add' ? 2.5 : 2} aria-hidden="true" {...props} />;
}
